backend:
  name: git-gateway
  branch: netlify-version
publish_mode: editorial_workflow
media_folder: "dist/img"
public_folder: "/img"
collections:
  - name: "pages"
    label: "Pages"
    widget: list
    folder: "src/assets/pages"
    format: json
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "blogPost", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image" }