backend:
  name: git-gateway
  branch: netlify-version
publish_mode: editorial_workflow
media_folder: "src/assets/img"
public_folder: ""
collections:
  - name: "pages"
    label: "Pages"
    folder: "src/assets/pages"
    format: json
    slug: "{{filename}}"
    fields:
      - { label: "Page", name: 'title', widget: "string" }
      - label: "Cards"
        name: "cards"
        widget: "list"
        fields:
        - { label: "Title", name: "title", widget: "string" }
        - { label: "Description", name: "blogPost", widget: "string" }
        - { label: "Featured Image", name: "photo", widget: "image" }